name: Build for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Cache vcpkg
        id: cache-vcpkg
        uses: actions/cache@v3
        with:
          path: |
            ./vcpkg
          key: ${{ runner.os }}-vcpkg

      - name: Install vcpkg
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/Microsoft/vcpkg.git --depth=1
          ./vcpkg/bootstrap-vcpkg.bat
          ./vcpkg/vcpkg version

      - name: Update vcpkg
        if: steps.cache-vcpkg.outputs.cache-hit == 'true'
        run: |
          cd ./vcpkg
          ./vcpkg version
          git pull
          ./bootstrap-vcpkg.bat
          ./vcpkg version
          cd ..

      - name: Update packages
        if: steps.cache-vcpkg.outputs.cache-hit == 'true'
        run: |
          cd ./vcpkg
          ./vcpkg update
          ./vcpkg upgrade
          ./vcpkg upgrade --no-dry-run
          cd ..

      - name: Install packages via vcpkg
        run: |
          cd ./vcpkg
          ./vcpkg install opencv[core,contrib,eigen,qt,openmp,freetype,jasper,tbb]:x64-windows --clean-buildtrees-after-build
          cd ..

      - name: Archive installed
        run: |
          7z a ./vcpkg-pkgs-windows.7z ./vcpkg/installed ./vcpkg/scripts

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: vcpkg-pkgs-windows
          path: |
            ./vcpkg-pkgs-windows.7z

      - name: Cleanup installed
        run: |
          rm -Recurse -Force ./vcpkg/installed
