name: Build for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Make directory in drive C
        run: |
          mkdir C:/dev

      - name: Cache vcpkg
        id: cache-vcpkg
        uses: actions/cache@v3
        with:
          path: |
            C:/dev/vcpkg
          key: ${{ runner.os }}-vcpkg

      - name: Install vcpkg
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        run: |
          cd C:/dev
          git clone https://github.com/Microsoft/vcpkg.git --depth=1
          ./vcpkg/bootstrap-vcpkg.bat
          ./vcpkg/vcpkg version
          cd -

      - name: Download previously artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.MY_TOKEN}}
          run_id: 4704916113
          name: vcpkg-pkgs-windows

      - name: Extract previously 'installed' files
        run: |
          rm -Recurse -Force C:/dev/vcpkg/scripts
          7z x ./vcpkg-pkgs-windows.7z -o'C:/dev/vcpkg/' -y

      - name: Update vcpkg
        if: steps.cache-vcpkg.outputs.cache-hit == 'true'
        run: |
          cd C:/dev/vcpkg
          ./vcpkg version
          git pull
          ./bootstrap-vcpkg.bat
          ./vcpkg version
          cd -

      - name: Update packages
        if: steps.cache-vcpkg.outputs.cache-hit == 'true'
        run: |
          cd C:/dev/vcpkg
          ./vcpkg update
          ./vcpkg upgrade
          ./vcpkg upgrade --no-dry-run --binarysource=clear
          cd -

      - name: Install packages via vcpkg
        run: |
          cd C:/dev/vcpkg
          ./vcpkg install opencv[core,contrib,eigen,openmp,qt,freetype,jasper,tbb,ipp]:x64-windows --recurse --clean-after-build --binarysource=clear
          cd -

      - name: Archive installed
        run: |
          7z a ./vcpkg-pkgs-windows.7z C:/dev/vcpkg

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: vcpkg-pkgs-windows
          path: |
            ./vcpkg-pkgs-windows.7z
