name: Build for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git --depth=1
          ./vcpkg/bootstrap-vcpkg.bat
          ./vcpkg/vcpkg version
