# This is a basic workflow to help you get started with Actions

name: Release workflow artifact

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tag:
        description: Target release tag
        type: string
      artifact_id:
        description: Artifact ID
        required: true
      asset_label:
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  download_artifact_and_release:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Download previously artifact
        run: |
          curl -L "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ inputs.artifact_id }}/zip" -o artifact.zip -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"
          7z x artifact.zip
          rm artifact.zip

      - name: Temporarily resolve wrongly zipped artifacts
        run: |
          7z x -mmt=4 vcpkg-pkgs-windows.7z
          rm vcpkg-pkgs-windows.7z
          7z a -mmt=4 vcpkg-pkgs-windows.7z ./vcpkg

      - name: Release using GitHub CLI
        shell: bash
        run: |
          gh release upload ${{ inputs.tag }} "vcpkg-pkgs-windows.7z#${{ inputs.notes }}"
