# This is a basic workflow to help you get started with Actions

name: Release workflow artifact

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tag:
        description: Target release tag
        type: string
      run_id:
        description: Workflow run ID
        required: true
      artifact_name:
        default: vcpkg-pkgs-windows
        type: string
      asset_label:
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  download_artifact_and_release:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Download previously artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ inputs.run_id }}
          name: vcpkg-pkgs-windows

      - name: Release using GitHub CLI
        shell: bash
        run: |
          gh release upload ${{ inputs.tag }} "vcpkg-pkgs-windows.7z#${{ inputs.notes }}"
